import type { Metadata } from "next";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { geistSans, roboto } from "@/lib/font/font";

import "./globals.css";

export const metadata: Metadata = {
  title: "Social Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${roboto.variable} antialiased h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
